### PR TITLE
Upstream update

### PR DESCRIPTION
**Pull request by casperdcl**
work in progress

### CODE REVIEW

**Comment by KrisThielemans** [comment]
hi. I'm somewhat confused by this. We've merged upstream_update to this branch on Friday. So I guess most of these commits should have been there already. We did resolve  a few conflicts then (not so clear why we had them, seems to have been some file creation on both branches, but we're surprised), so these conflicts are strange...

**Comment by casperdcl** [comment]
Hi, I think there's four branches:
1. https://github.com/CCPPETMR/xSTIR/tree/my-STIR-interfaces
2. https://github.com/CCPPETMR/xSTIR/tree/upstream_update
3. https://github.com/evgueni-ovtchinnikov/xSTIR/tree/my-STIR-interfaces
4. https://github.com/evgueni-ovtchinnikov/xSTIR/tree/upstream_update
and this PR is to merge 2 into 1... If there are conflicts which have already been resolved then this branch (2) should be rebased onto (1) and conflicts fixed before merging.

**Comment by KrisThielemans** [comment]
I think Evgueni's original branches are no longer used. we intended to merge 2 into 1.

I'm loath to use rebase. as far as I understand, it's dangerous to use for branches that have been checked out already by others, but I'd be happy to be corrected (during a meeting).

One solution would be to make a "master" branch, and just put the upstream_update code on there, and get rid of the my-STIR-interfaces branch.

**Comment by KrisThielemans** [comment]
I've created a new master branch from upstream_update. I intend to delete this PR therefore. Later on we should discard the my-STIR-interfaces branch.

@casperdcl can you check if master contains what you need?

**Pull request closed without merging**
